spring:
  application:
    name: spring-pet-adoption
  datasource:
    url: jdbc:postgresql://localhost:5432:/pet-adoption
    username: adoption
    password: verySecure123!
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect